services:
   
  diagnosis_backend:
    build:
      context: ./diagnostico_pesv
      dockerfile: Dockerfile
    command: sh -c "/usr/local/bin/wait-for-it.sh 162.215.135.37:33080 -- python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear && daphne -p 8000 diagnostico_pesv.asgi:application"
    restart: always
    container_name: pesvapp
    volumes:
      - ./diagnostico_pesv:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DEBUG=${DEBUG}
    depends_on: []