# Generated by Django 5.0.6 on 2024-08-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'sign', 'verbose_name_plural': 'signs'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=None, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='licensia_sst',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
