# Generated by Django 5.0.6 on 2024-07-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('name', models.CharField(max_length=100, null=None, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('name', models.CharField(max_length=100, null=None, unique=True)),
                ('nit', models.CharField(max_length=20, null=None, unique=True)),
                ('size', models.IntegerField()),
                ('dependant', models.CharField(max_length=200, null=True)),
                ('dependant_phone', models.CharField(max_length=20, null=True)),
                ('actividades_ciiu', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('acquired_certification', models.CharField(max_length=255, null=True)),
                ('diagnosis', models.CharField(max_length=255, null=True)),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.segments')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
