# Generated by Django 5.0.6 on 2024-07-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='actividades_ciiu',
            new_name='activities_ciiu',
        ),
    ]
