# Generated by Django 5.0.6 on 2024-07-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysize_dedication_company_company_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='size',
        ),
    ]
