# Generated by Django 5.0.6 on 2024-07-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_vehiclequestions_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverQuestion',
        ),
    ]
