# Generated by Django 5.0.6 on 2024-07-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_driverquestion_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='vehicle_questions',
            new_name='vehicle_question',
        ),
    ]
