# Generated by Django 5.0.6 on 2024-07-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_vehicle_questions_fleet_vehicle_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_questions',
            new_name='driver_question',
        ),
    ]
