# Generated by Django 5.0.6 on 2024-07-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_rename_driver_questions_driver_driver_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dependant_position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
