# Generated by Django 5.0.6 on 2024-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_company_company_size_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='quantity_arrended',
            field=models.IntegerField(default=0, null=None),
        ),
        migrations.AddField(
            model_name='fleet',
            name='quantity_contractors',
            field=models.IntegerField(default=0, null=None),
        ),
        migrations.AddField(
            model_name='fleet',
            name='quantity_intermediation',
            field=models.IntegerField(default=0, null=None),
        ),
        migrations.AddField(
            model_name='fleet',
            name='quantity_leasing',
            field=models.IntegerField(default=0, null=None),
        ),
        migrations.AddField(
            model_name='fleet',
            name='quantity_renting',
            field=models.IntegerField(default=0, null=None),
        ),
    ]
