# Generated by Django 5.0.6 on 2024-07-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_fleet_quantity_arrended_fleet_quantity_contractors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysize',
            name='vehicle_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='quantity_arrended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='quantity_contractors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='quantity_intermediation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='quantity_leasing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='quantity_owned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='quantity_renting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='quantity_third_party',
            field=models.IntegerField(default=0),
        ),
    ]
