# Generated by Django 5.0.6 on 2024-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_companysize_vehicle_min_alter_driver_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysize',
            name='driver_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysize',
            name='driver_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysize',
            name='vehicle_max',
            field=models.IntegerField(default=0),
        ),
    ]
