# Generated by Django 5.0.6 on 2024-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_companysize_driver_max_companysize_driver_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysize',
            name='driver_max',
            field=models.IntegerField(db_comment='El valor -1 representa sin Limite', default=0),
        ),
        migrations.AlterField(
            model_name='companysize',
            name='vehicle_max',
            field=models.IntegerField(db_comment='El valor -1 representa sin Limite', default=0),
        ),
    ]
