# Generated by Django 5.0.6 on 2024-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_alter_companysize_driver_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='diagnosis_step',
            field=models.IntegerField(default=1, max_length=2, null=None),
        ),
    ]
