# Generated by Django 5.0.6 on 2024-07-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arl', '0001_initial'),
        ('company', '0025_alter_company_diagnosis_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='arl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arl.arl'),
        ),
    ]
