# Generated by Django 5.0.6 on 2024-07-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_company_arl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('description', models.TextField()),
                ('vehicle_min', models.IntegerField(default=0)),
                ('vehicle_max', models.IntegerField(db_comment='El valor NULL representa sin Limite', default=0, null=True)),
                ('driver_min', models.IntegerField(default=0)),
                ('driver_max', models.IntegerField(db_comment='El valor NULL representa sin Limite', default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='company',
            old_name='dedication',
            new_name='mission',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='companysize',
            name='dedication',
        ),
        migrations.RemoveField(
            model_name='companysize',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companysize',
            name='driver_max',
        ),
        migrations.RemoveField(
            model_name='companysize',
            name='driver_min',
        ),
        migrations.RemoveField(
            model_name='companysize',
            name='vehicle_max',
        ),
        migrations.RemoveField(
            model_name='companysize',
            name='vehicle_min',
        ),
        migrations.RenameModel(
            old_name='Dedication',
            new_name='Mission',
        ),
        migrations.CreateModel(
            name='MisionalitySizeCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misionalidad_criteria', to='company.mission')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companysize')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.sizecriteria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
