# Generated by Django 5.0.6 on 2024-07-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_sizecriteria_rename_dedication_company_mission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizecriteria',
            old_name='description',
            new_name='name',
        ),
    ]
