# Generated by Django 5.0.6 on 2024-07-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_rename_description_sizecriteria_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companysize'),
        ),
    ]
