# Generated by Django 5.0.6 on 2024-07-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_company_company_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_size',
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companysize'),
        ),
    ]
