# Generated by Django 5.0.6 on 2024-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_remove_company_company_size_company_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('name', models.CharField(max_length=250, null=True)),
                ('code', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
