# Generated by Django 5.0.6 on 2024-07-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_ciiu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCiiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciiu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.ciiu')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
        ),
    ]
