# Generated by Django 5.0.6 on 2024-07-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_companyciiu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='activities_ciiu',
        ),
    ]
