# Generated by Django 5.0.6 on 2024-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_activities_ciiu'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ciius',
            field=models.ManyToManyField(related_name='companies', to='company.ciiu'),
        ),
        migrations.DeleteModel(
            name='CompanyCiiu',
        ),
    ]
