# Generated by Django 5.0.6 on 2024-08-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_remove_fleet_company_remove_fleet_vehicle_question_and_more'),
        ('diagnosis', '0019_driverquestion_vehiclequestions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverQuestion',
        ),
        migrations.DeleteModel(
            name='VehicleQuestions',
        ),
    ]
