# Generated by Django 5.1 on 2024-08-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_delete_driverquestion_delete_vehiclequestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='diagnosis_step',
        ),
    ]
