# Generated by Django 5.1 on 2024-08-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_remove_company_diagnosis_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='consultor',
        ),
    ]
