# Generated by Django 5.1 on 2024-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_company_enable_for_counting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enable_for_counting',
            field=models.BooleanField(default=True),
        ),
    ]
