# Generated by Django 5.0.6 on 2024-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_requirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis_requirement',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
