# Generated by Django 5.0.6 on 2024-07-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_requirement', '0003_diagnosis_requirement_advanced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis_requirement',
            name='step',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
