# Generated by Django 5.0.6 on 2024-07-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_requirement', '0004_diagnosis_requirement_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis_requirement',
            name='cycle',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
    ]
