# Generated by Django 5.1 on 2024-08-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_remove_company_consultor'),
        ('diagnosis_requirement', '0006_recomendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendation',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendation_type', to='company.companysize'),
        ),
    ]
