# Generated by Django 5.1 on 2024-08-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_requirement', '0007_recomendation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendation',
            name='type',
        ),
        migrations.AddField(
            model_name='recomendation',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recomendation',
            name='all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recomendation',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recomendation',
            name='standard',
            field=models.BooleanField(default=False),
        ),
    ]
