# Generated by Django 5.1 on 2024-08-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_requirement', '0008_remove_recomendation_type_recomendation_advanced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan_Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('name', models.TextField(null=True)),
                ('requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis_requirement.diagnosis_requirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
