# Generated by Django 5.1 on 2024-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
