# Generated by Django 5.1 on 2024-08-20 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_group', '0004_rename_corporatecompanydiagnosis_corporate_company_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate_company_diagnosis',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_diagnoses_corporate', to='corporate_group.corporate'),
        ),
    ]
