# Generated by Django 5.1 on 2024-08-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_remove_company_consultor'),
        ('corporate_group', '0005_alter_corporate_company_diagnosis_corporate'),
        ('diagnosis', '0028_diagnosis_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='companies',
            field=models.ManyToManyField(related_name='corporates', through='corporate_group.Corporate_Company_Diagnosis', to='company.company'),
        ),
        migrations.AddField(
            model_name='corporate',
            name='diagnoses',
            field=models.ManyToManyField(related_name='corporates', through='corporate_group.Corporate_Company_Diagnosis', to='diagnosis.diagnosis'),
        ),
        migrations.AlterField(
            model_name='corporate_company_diagnosis',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_company_diagnoses', to='company.company'),
        ),
        migrations.AlterField(
            model_name='corporate_company_diagnosis',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_company_diagnoses', to='diagnosis.diagnosis'),
        ),
    ]
