# Generated by Django 5.1 on 2024-08-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_group', '0007_remove_corporate_diagnoses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='nit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
