# Generated by Django 5.0.6 on 2024-07-15 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis_requirement', '0002_alter_diagnosis_requirement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('cycle', models.IntegerField(default=None, null=True)),
                ('step', models.IntegerField(default=None, null=True)),
                ('variable_value', models.IntegerField(default=0)),
                ('requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='diagnosis_requirement.diagnosis_requirement')),
                ('diagnosis_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.diagnosis_type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
