# Generated by Django 5.0.6 on 2024-07-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_compliance_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis_questions',
            name='cycle',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
    ]
