# Generated by Django 5.0.6 on 2024-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_alter_diagnosis_questions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='observation',
            field=models.TextField(default='SIN OBSERVACIONES'),
        ),
    ]
