# Generated by Django 5.0.6 on 2024-07-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_checklist_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis_questions',
            name='diagnosis_type',
        ),
        migrations.AddField(
            model_name='diagnosis_questions',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis_questions',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis_questions',
            name='standard',
            field=models.BooleanField(default=False),
        ),
    ]
