# Generated by Django 5.0.6 on 2024-07-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_remove_diagnosis_questions_diagnosis_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis_questions',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='diagnosis_questions',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='diagnosis_questions',
            name='standard',
        ),
    ]
