# Generated by Django 5.0.6 on 2024-07-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_remove_diagnosis_questions_advanced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis_questions',
            name='step',
        ),
    ]
