# Generated by Django 5.0.6 on 2024-07-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0008_remove_diagnosis_questions_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis_questions',
            name='cycle',
        ),
    ]
