# Generated by Django 5.0.6 on 2024-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0013_remove_checklist_company_checklist_diagnosis_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
