# Generated by Django 5.0.6 on 2024-07-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0014_diagnosis_is_finalized'),
        ('diagnosis_requirement', '0006_recomendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checlist_Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('observation', models.TextField(null=True)),
                ('compliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.compliance')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
                ('requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis_requirement.diagnosis_requirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
