# Generated by Django 5.0.6 on 2024-07-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0015_checlist_requirement'),
        ('diagnosis_requirement', '0006_recomendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checlist_Requirement',
            new_name='Checklist_Requirement',
        ),
    ]
