# Generated by Django 5.0.6 on 2024-08-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0017_delete_diagnosis_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="schedule",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="sequence",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
