# Generated by Django 5.1 on 2024-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0020_fleet_quantity_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_step',
            field=models.IntegerField(default=0),
        ),
    ]
