# Generated by Django 5.1 on 2024-08-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_remove_company_diagnosis_step'),
        ('diagnosis', '0021_diagnosis_diagnosis_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_type', to='company.companysize'),
        ),
    ]
