# Generated by Django 5.1 on 2024-08-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0022_diagnosis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis'),
        ),
    ]
