# Generated by Django 5.1 on 2024-08-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0026_alter_diagnosis_consultor'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='mode_ejecution',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=100),
        ),
    ]
