# Generated by Django 5.1 on 2024-08-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0027_diagnosis_mode_ejecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='observation',
            field=models.TextField(null=True),
        ),
    ]
