# Generated by Django 5.1 on 2024-08-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0029_remove_driver_diagnosis_remove_fleet_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='diagnosis_counter',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='diagnosis_counter',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_question',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='vehicle_question',
        ),
        migrations.DeleteModel(
            name='Diagnosis_Counter',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Fleet',
        ),
    ]
