# Generated by Django 5.1 on 2024-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0030_remove_fleet_diagnosis_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='in_progress',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
