# Generated by Django 5.1 on 2024-08-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0031_diagnosis_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='date_elabored',
            field=models.DateField(),
        ),
    ]
