# Generated by Django 5.1 on 2024-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0032_alter_diagnosis_date_elabored'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='is_for_corporate_group',
            field=models.BooleanField(default=False),
        ),
    ]
