# Generated by Django 5.1 on 2024-08-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_group', '0007_remove_corporate_diagnoses_and_more'),
        ('diagnosis', '0033_diagnosis_is_for_corporate_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='corporate_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporates_diagnosis', to='corporate_group.corporate'),
        ),
    ]
