# Generated by Django 5.0.6 on 2024-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_user_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
