# Generated by Django 5.1 on 2024-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
    ]
