# Generated by Django 5.1 on 2024-09-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_user_external_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_step',
            field=models.IntegerField(default=0),
        ),
    ]
