# Generated by Django 5.1 on 2024-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0008_querylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='http_method',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='query_params',
            field=models.JSONField(default=None, null=True),
        ),
    ]
