# Generated by Django 5.1 on 2024-09-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0009_querylog_http_method_querylog_query_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
