# Generated by Django 5.1 on 2024-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0010_querylog_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('label', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
