# Generated by Django 5.1 on 2024-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sign', '0011_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(related_name='menus', to='auth.group'),
        ),
    ]
