# Generated by Django 5.1 on 2024-08-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0039_remove_company_consultor'),
        ('diagnosis', '0030_remove_fleet_diagnosis_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis_Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_counter', to='company.company')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('quantity', models.IntegerField(default=0)),
                ('diagnosis_counter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis_counter.diagnosis_counter')),
                ('driver_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.driverquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('quantity_owned', models.IntegerField(default=0)),
                ('quantity_third_party', models.IntegerField(default=0)),
                ('quantity_arrended', models.IntegerField(default=0)),
                ('quantity_contractors', models.IntegerField(default=0)),
                ('quantity_intermediation', models.IntegerField(default=0)),
                ('quantity_leasing', models.IntegerField(default=0)),
                ('quantity_renting', models.IntegerField(default=0)),
                ('quantity_employees', models.IntegerField(default=0)),
                ('diagnosis_counter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis_counter.diagnosis_counter')),
                ('vehicle_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.vehiclequestions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
