# Generated by Django 5.1 on 2024-08-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_remove_company_consultor'),
        ('diagnosis_counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis_counter',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companysize'),
        ),
    ]
