services:
  db:
    image: mysql:8.4.2 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "33080:3306"  # Mapea el puerto 33080 de tu máquina al puerto 3306 del contenedor
    
  diagnosis_backend:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: pesvapp
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # El puerto del contenedor Django expuesto en tu máquina local
    depends_on:
      - db
    env_file:
      - ../.env
    command: sh -c "/usr/local/bin/wait-for-it.sh db:3306 -- python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always

